//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.12.20 at 09:36:36 PM CET 
//


package org.inria.fr.ns.sr;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for lien_structure_exterieure complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="lien_structure_exterieure"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="date_debut" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="date_fin" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="type_lien" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="structure_exterieure" type="{http://ns.inria.fr/dsi/si/app/bastri}structure_exterieure"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="version" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "lien_structure_exterieure", propOrder = {
    "dateDebut",
    "dateFin",
    "typeLien",
    "structureExterieure"
})
public class LienStructureExterieure {

    @XmlElement(name = "date_debut", required = true)
    protected String dateDebut;
    @XmlElement(name = "date_fin", required = true)
    protected String dateFin;
    @XmlElement(name = "type_lien", required = true)
    protected String typeLien;
    @XmlElement(name = "structure_exterieure", required = true)
    protected StructureExterieure structureExterieure;
    @XmlAttribute(name = "version")
    protected String version;

    /**
     * Gets the value of the dateDebut property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDateDebut() {
        return dateDebut;
    }

    /**
     * Sets the value of the dateDebut property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDateDebut(String value) {
        this.dateDebut = value;
    }

    /**
     * Gets the value of the dateFin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDateFin() {
        return dateFin;
    }

    /**
     * Sets the value of the dateFin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDateFin(String value) {
        this.dateFin = value;
    }

    /**
     * Gets the value of the typeLien property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTypeLien() {
        return typeLien;
    }

    /**
     * Sets the value of the typeLien property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTypeLien(String value) {
        this.typeLien = value;
    }

    /**
     * Gets the value of the structureExterieure property.
     * 
     * @return
     *     possible object is
     *     {@link StructureExterieure }
     *     
     */
    public StructureExterieure getStructureExterieure() {
        return structureExterieure;
    }

    /**
     * Sets the value of the structureExterieure property.
     * 
     * @param value
     *     allowed object is
     *     {@link StructureExterieure }
     *     
     */
    public void setStructureExterieure(StructureExterieure value) {
        this.structureExterieure = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

}
