//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.12.20 at 09:36:36 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://ns.inria.fr/dsi/si/app/bastri", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.inria.fr.ns.sr;
