//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.12.20 at 09:36:36 PM CET 
//


package org.inria.fr.ns.sr;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for researchStructureCategory.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="researchStructureCategory"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="EP"/&gt;
 *     &lt;enumeration value="Equipe"/&gt;
 *     &lt;enumeration value="Action exploratoire"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "researchStructureCategory")
@XmlEnum
public enum ResearchStructureCategory {

    EP("EP"),
    @XmlEnumValue("Equipe")
    EQUIPE("Equipe"),
    @XmlEnumValue("Action exploratoire")
    ACTION_EXPLORATOIRE("Action exploratoire");
    private final String value;

    ResearchStructureCategory(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ResearchStructureCategory fromValue(String v) {
        for (ResearchStructureCategory c: ResearchStructureCategory.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
