//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.12.25 at 11:46:04 AM CET 
//


package org.inria.fr.ns.sr;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="siidEquipeGroupe" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="urlTeam" type="{http://ns.inria.fr/dsi/si/app/bastri}urlTeam" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="keywords" type="{http://ns.inria.fr/dsi/si/app/bastri}keywords" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="sigle" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="sigle_html" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="sigle_latex" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="typestructure" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="libellefr" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="libelleen" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="domaine" type="{http://ns.inria.fr/dsi/si/app/bastri}domaine" maxOccurs="2"/&gt;
 *         &lt;element name="theme" type="{http://ns.inria.fr/dsi/si/app/bastri}theme" maxOccurs="2"/&gt;
 *         &lt;element name="date_creation" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="date_fermeture" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="entite" type="{http://ns.inria.fr/dsi/si/app/bastri}entite" maxOccurs="unbounded"/&gt;
 *         &lt;element name="idhal" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="resume" type="{http://ns.inria.fr/dsi/si/app/bastri}resume" maxOccurs="2" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="siid" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="numnatstruct" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "siidEquipeGroupe",
    "urlTeam",
    "keywords",
    "sigle",
    "sigleHtml",
    "sigleLatex",
    "typestructure",
    "libellefr",
    "libelleen",
    "domaine",
    "theme",
    "dateCreation",
    "dateFermeture",
    "entite",
    "idhal",
    "resume"
})
@XmlRootElement(name = "structureinria")
public class Structureinria {

    @XmlElement(required = true)
    protected String siidEquipeGroupe;
    protected List<UrlTeam> urlTeam;
    protected List<Keywords> keywords;
    @XmlElement(required = true)
    protected String sigle;
    @XmlElement(name = "sigle_html", required = true)
    protected String sigleHtml;
    @XmlElement(name = "sigle_latex", required = true)
    protected String sigleLatex;
    @XmlElement(required = true)
    protected String typestructure;
    protected String libellefr;
    protected String libelleen;
    @XmlElement(required = true)
    protected List<Domaine> domaine;
    @XmlElement(required = true)
    protected List<Theme> theme;
    @XmlElement(name = "date_creation")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dateCreation;
    @XmlElement(name = "date_fermeture")
    protected String dateFermeture;
    @XmlElement(required = true)
    protected List<Entite> entite;
    protected String idhal;
    protected List<Resume> resume;
    @XmlAttribute(name = "siid")
    protected String siid;
    @XmlAttribute(name = "numnatstruct")
    protected String numnatstruct;

    /**
     * Gets the value of the siidEquipeGroupe property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSiidEquipeGroupe() {
        return siidEquipeGroupe;
    }

    /**
     * Sets the value of the siidEquipeGroupe property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSiidEquipeGroupe(String value) {
        this.siidEquipeGroupe = value;
    }

    /**
     * Gets the value of the urlTeam property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the urlTeam property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUrlTeam().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link UrlTeam }
     * 
     * 
     */
    public List<UrlTeam> getUrlTeam() {
        if (urlTeam == null) {
            urlTeam = new ArrayList<UrlTeam>();
        }
        return this.urlTeam;
    }

    /**
     * Gets the value of the keywords property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the keywords property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getKeywords().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Keywords }
     * 
     * 
     */
    public List<Keywords> getKeywords() {
        if (keywords == null) {
            keywords = new ArrayList<Keywords>();
        }
        return this.keywords;
    }

    /**
     * Gets the value of the sigle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSigle() {
        return sigle;
    }

    /**
     * Sets the value of the sigle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSigle(String value) {
        this.sigle = value;
    }

    /**
     * Gets the value of the sigleHtml property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSigleHtml() {
        return sigleHtml;
    }

    /**
     * Sets the value of the sigleHtml property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSigleHtml(String value) {
        this.sigleHtml = value;
    }

    /**
     * Gets the value of the sigleLatex property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSigleLatex() {
        return sigleLatex;
    }

    /**
     * Sets the value of the sigleLatex property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSigleLatex(String value) {
        this.sigleLatex = value;
    }

    /**
     * Gets the value of the typestructure property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTypestructure() {
        return typestructure;
    }

    /**
     * Sets the value of the typestructure property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTypestructure(String value) {
        this.typestructure = value;
    }

    /**
     * Gets the value of the libellefr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLibellefr() {
        return libellefr;
    }

    /**
     * Sets the value of the libellefr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLibellefr(String value) {
        this.libellefr = value;
    }

    /**
     * Gets the value of the libelleen property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLibelleen() {
        return libelleen;
    }

    /**
     * Sets the value of the libelleen property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLibelleen(String value) {
        this.libelleen = value;
    }

    /**
     * Gets the value of the domaine property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the domaine property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDomaine().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Domaine }
     * 
     * 
     */
    public List<Domaine> getDomaine() {
        if (domaine == null) {
            domaine = new ArrayList<Domaine>();
        }
        return this.domaine;
    }

    /**
     * Gets the value of the theme property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the theme property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTheme().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Theme }
     * 
     * 
     */
    public List<Theme> getTheme() {
        if (theme == null) {
            theme = new ArrayList<Theme>();
        }
        return this.theme;
    }

    /**
     * Gets the value of the dateCreation property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDateCreation() {
        return dateCreation;
    }

    /**
     * Sets the value of the dateCreation property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDateCreation(XMLGregorianCalendar value) {
        this.dateCreation = value;
    }

    /**
     * Gets the value of the dateFermeture property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDateFermeture() {
        return dateFermeture;
    }

    /**
     * Sets the value of the dateFermeture property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDateFermeture(String value) {
        this.dateFermeture = value;
    }

    /**
     * Gets the value of the entite property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the entite property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEntite().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Entite }
     * 
     * 
     */
    public List<Entite> getEntite() {
        if (entite == null) {
            entite = new ArrayList<Entite>();
        }
        return this.entite;
    }

    /**
     * Gets the value of the idhal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdhal() {
        return idhal;
    }

    /**
     * Sets the value of the idhal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdhal(String value) {
        this.idhal = value;
    }

    /**
     * Gets the value of the resume property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the resume property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getResume().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Resume }
     * 
     * 
     */
    public List<Resume> getResume() {
        if (resume == null) {
            resume = new ArrayList<Resume>();
        }
        return this.resume;
    }

    /**
     * Gets the value of the siid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSiid() {
        return siid;
    }

    /**
     * Sets the value of the siid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSiid(String value) {
        this.siid = value;
    }

    /**
     * Gets the value of the numnatstruct property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumnatstruct() {
        return numnatstruct;
    }

    /**
     * Sets the value of the numnatstruct property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumnatstruct(String value) {
        this.numnatstruct = value;
    }

}
